baseURL = "https://sherlockworld.github.io/sherlockweb/"
languageCode = "en-us"
title = "Sherlock"
theme = "ananke"

[params]
  favicon = ""
  site_logo = ""
  description = "Sherlock"
  facebook = ""
  twitter = "https://twitter.com/SherlockH1854"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2